/*
 * File: app/view/ContactoFormWindow.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RestFullAdmin.view.ContactoFormWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.contactoformwindow',

    requires: [
        'RestFullAdmin.view.ContactoFormWindowViewModel',
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.form.field.Checkbox',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Fill'
    ],

    viewModel: {
        type: 'contactoformwindow'
    },
    autoShow: true,
    height: 210,
    width: 592,
    layout: 'fit',
    title: 'Formulario de Contacto',
    modal: true,
    defaultListenerScope: true,

    items: [
        {
            xtype: 'form',
            bodyPadding: 10,
            title: '',
            items: [
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Nombre',
                    name: 'Nombre'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Correo',
                    name: 'Correo'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Teléfono',
                    name: 'Telefono'
                },
                {
                    xtype: 'checkboxfield',
                    anchor: '100%',
                    fieldLabel: '',
                    name: 'Activo',
                    boxLabel: 'Activo'
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'bottom',
            items: [
                {
                    xtype: 'button',
                    text: 'Guardar',
                    listeners: {
                        click: 'onSaveButtonClick'
                    }
                },
                {
                    xtype: 'button',
                    text: 'Cancelar',
                    listeners: {
                        click: 'onCancelButtonClick'
                    }
                },
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'button',
                    text: 'Eliminar'
                }
            ]
        }
    ],

    onSaveButtonClick: function(button, e, eOpts) {
            var win = button.up('window'),
                form = win.down('form');
                        console.log(form.getForm().getValues());
            var myModel = form.getRecord();

            form.updateRecord(myModel);
                myModel.save({
                    success: function(record, operation){
                        record.commit();
                    },
                    failure: function(record, operation){
                        Ext.Msg.alert('Ooops','Ha ocurrido un error en la actualización');

                    }

                });
            form.up('window').close();

    },

    onCancelButtonClick: function(button, e, eOpts) {
             button.up('window').close();
    }

});