/*
 * File: app/view/Main.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RestFullAdmin.view.Main', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.main',

    requires: [
        'RestFullAdmin.view.MainViewModel',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Boolean',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'main'
    },
    layout: 'fit',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'gridpanel',
            title: 'Contacto',
            store: 'Contactos',
            listeners: {
                added: 'onGridpanelAdded',
                itemclick: 'onContactoGridItemclick'
            },
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Id',
                    text: 'ID',
                    flex: 2
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Nombre',
                    text: 'Nombre',
                    flex: 15
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Correo',
                    text: 'Correo',
                    flex: 12
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Telefono',
                    text: 'Telefono',
                    flex: 6
                },
                {
                    xtype: 'booleancolumn',
                    dataIndex: 'Activo',
                    text: 'Activo',
                    falseText: 'No',
                    trueText: 'Si'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            text: 'Nuevo Contacto',
                            listeners: {
                                click: 'onSaveButtonclick'
                            }
                        }
                    ]
                }
            ]
        }
    ],

    onGridpanelAdded: function(component, container, pos, eOpts) {

    },

    onSaveButtonclick: function(button, e, eOpts) {
           var win = Ext.create('RestFullAdmin.view.ContactoFormWindow');
    },

    onContactoGridItemclick: function(dataview, record, item, index, e, eOpts) {
            var win = Ext.create('RestFullAdmin.view.ContactoFormWindow');
            win.down('form').loadRecord(record);
    }

});