/*
 * File: app/model/Contacto.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RestFullAdmin.model.Contacto', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Boolean',
        'Ext.data.proxy.Rest',
        'Ext.data.reader.Json'
    ],

    idProperty: 'Id',

    fields: [
        {
            name: 'Id'
        },
        {
            name: 'Nombre'
        },
        {
            name: 'Correo'
        },
        {
            name: 'Telefono'
        },
        {
            type: 'boolean',
            name: 'Activo'
        }
    ],

    proxy: {
        type: 'rest',
        url: 'http://localhost:57288/api/Contactoes/',
        reader: {
            type: 'json'
        }
    }
});